/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;
import Stacks.*;
import EvalExpreArit.*;

/**
 *
 * @author Ricardo Sanchez Lopez
 */
public class CalculadoraFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraFrame
     */
    public CalculadoraFrame() {
        System.out.println("INICIANDO CALCULADORA");
        expreStr="";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        norte = new javax.swing.JPanel();
        pantalla = new javax.swing.JTextField();
        sur = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        centro = new javax.swing.JPanel();
        parDer = new javax.swing.JButton();
        parIzq = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        siete = new javax.swing.JButton();
        multi = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        div = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        uno = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        cambio = new javax.swing.JButton();
        resta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(65, 139, 150));
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(450, 550));

        norte.setBackground(new java.awt.Color(29, 56, 73));

        pantalla.setBackground(new java.awt.Color(174, 189, 99));
        pantalla.setColumns(22);
        pantalla.setFont(new java.awt.Font("Lucida Console", 0, 24)); // NOI18N
        pantalla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        pantalla.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pantalla.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout norteLayout = new javax.swing.GroupLayout(norte);
        norte.setLayout(norteLayout);
        norteLayout.setHorizontalGroup(
            norteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, norteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                .addContainerGap())
        );
        norteLayout.setVerticalGroup(
            norteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(norteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(norte, java.awt.BorderLayout.PAGE_START);

        sur.setBackground(new java.awt.Color(29, 56, 73));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("CASI");
        sur.add(jLabel1);

        getContentPane().add(sur, java.awt.BorderLayout.PAGE_END);

        centro.setBackground(new java.awt.Color(29, 56, 73));
        centro.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        centro.setLayout(new java.awt.GridLayout(5, 4, 11, 11));

        parDer.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        parDer.setText("(");
        parDer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        parDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parDerActionPerformed(evt);
            }
        });
        centro.add(parDer);

        parIzq.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        parIzq.setText(")");
        parIzq.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        parIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parIzqActionPerformed(evt);
            }
        });
        centro.add(parIzq);

        clear.setBackground(new java.awt.Color(207, 129, 21));
        clear.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        clear.setText("Clear");
        clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        centro.add(clear);

        igual.setBackground(new java.awt.Color(207, 129, 21));
        igual.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        igual.setText("=");
        igual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });
        centro.add(igual);

        nueve.setBackground(new java.awt.Color(162, 187, 207));
        nueve.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        nueve.setText("9");
        nueve.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });
        centro.add(nueve);

        ocho.setBackground(new java.awt.Color(162, 187, 207));
        ocho.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        ocho.setText("8");
        ocho.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });
        centro.add(ocho);

        siete.setBackground(new java.awt.Color(162, 187, 207));
        siete.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        siete.setText("7");
        siete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });
        centro.add(siete);

        multi.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        multi.setText("*");
        multi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiActionPerformed(evt);
            }
        });
        centro.add(multi);

        seis.setBackground(new java.awt.Color(162, 187, 207));
        seis.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        seis.setText("6");
        seis.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });
        centro.add(seis);

        cinco.setBackground(new java.awt.Color(162, 187, 207));
        cinco.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        cinco.setText("5");
        cinco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });
        centro.add(cinco);

        cuatro.setBackground(new java.awt.Color(162, 187, 207));
        cuatro.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        cuatro.setText("4");
        cuatro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });
        centro.add(cuatro);

        div.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        div.setText("/");
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });
        centro.add(div);

        tres.setBackground(new java.awt.Color(162, 187, 207));
        tres.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        tres.setText("3");
        tres.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });
        centro.add(tres);

        dos.setBackground(new java.awt.Color(162, 187, 207));
        dos.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        dos.setText("2");
        dos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });
        centro.add(dos);

        uno.setBackground(new java.awt.Color(162, 187, 207));
        uno.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        uno.setText("1");
        uno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });
        centro.add(uno);

        suma.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        suma.setText("+");
        suma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });
        centro.add(suma);

        cero.setBackground(new java.awt.Color(162, 187, 207));
        cero.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        cero.setText("0");
        cero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });
        centro.add(cero);

        punto.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        punto.setText(".");
        punto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });
        centro.add(punto);

        cambio.setBackground(new java.awt.Color(207, 129, 21));
        cambio.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        cambio.setText("+/-");
        cambio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambioActionPerformed(evt);
            }
        });
        centro.add(cambio);

        resta.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        resta.setText("-");
        resta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });
        centro.add(resta);

        getContentPane().add(centro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteActionPerformed
        expreStr= expreStr+ "7";
        pantalla.setText(expreStr);
        System.out.println(">> "+ expreStr);
    }//GEN-LAST:event_sieteActionPerformed

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroActionPerformed
        expreStr= expreStr+ "0";
        pantalla.setText(expreStr);
        System.out.println(">> "+ expreStr);
    }//GEN-LAST:event_ceroActionPerformed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        // TODO add your handling code here:
        expreStr= expreStr+ "1";
        pantalla.setText(expreStr);
        System.out.println(">> "+ expreStr);
    }//GEN-LAST:event_unoActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        // TODO add your handling code here:
        expreStr= expreStr+ "2";
        pantalla.setText(expreStr);
        System.out.println(">> "+ expreStr);
    }//GEN-LAST:event_dosActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        // TODO add your handling code here:
        expreStr= expreStr+ "3";
        pantalla.setText(expreStr);
        System.out.println(">> "+ expreStr);
    }//GEN-LAST:event_tresActionPerformed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        // TODO add your handling code here:
        expreStr= expreStr+ "4";
        pantalla.setText(expreStr);
        System.out.println(">> "+ expreStr);
    }//GEN-LAST:event_cuatroActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        // TODO add your handling code here:
        expreStr= expreStr+ "5";
        pantalla.setText(expreStr);
        System.out.println(">> "+ expreStr);
    }//GEN-LAST:event_cincoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        // TODO add your handling code here:
        expreStr= expreStr+ "6";
        pantalla.setText(expreStr);
        System.out.println(">> "+ expreStr);
    }//GEN-LAST:event_seisActionPerformed

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoActionPerformed
        // TODO add your handling code here:
        expreStr= expreStr+ "8";
        pantalla.setText(expreStr);
        System.out.println(">> "+ expreStr);
    }//GEN-LAST:event_ochoActionPerformed

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveActionPerformed
        // TODO add your handling code here:
        expreStr= expreStr+ "9";
        pantalla.setText(expreStr);
        System.out.println(">> "+ expreStr);
    }//GEN-LAST:event_nueveActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        // TODO add your handling code here:
        String delim = " ()+-*/";     // Delimitadores o separadores
        SplitTokens stk = new SplitTokens();
        RevisaSintaxisExpre rp1;
        boolean b;
        String Infix[], Postfix[];

        System.out.println("---- PRIMER PASO: String a Tokens ----");        
        System.out.println("    Expresion String a Evaluar: " + expreStr);
        Infix = stk.splitsarr(expreStr, delim);
        System.out.print("    ==Expresion String[] separada en Tokens: ,");
        for( String a: Infix) {  // foreach
            System.out.print(a + ",");
        }
        System.out.println("");
        
        System.out.println("---- SEGUNDO PASO: Revision de Sintaxis  ----");        
        rp1 = new RevisaSintaxisExpre(Infix);
        b = rp1.sintaxisExpre();
        System.out.println("    >>Expresion  Aritmetica: " + rp1.getErrorMsg() );
        
        if(b)
            expreStr= "Did good";
        else
            expreStr= rp1.getErrorMsg();
        
        pantalla.setText(expreStr);
        System.out.println(">> "+ expreStr);
    }//GEN-LAST:event_igualActionPerformed

    private void parDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parDerActionPerformed
        // TODO add your handling code here:
        expreStr= expreStr+ "(";
        pantalla.setText(expreStr);
        System.out.println(">> "+ expreStr);
    }//GEN-LAST:event_parDerActionPerformed

    private void parIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parIzqActionPerformed
        // TODO add your handling code here:
        expreStr= expreStr+ ")";
        pantalla.setText(expreStr);
        System.out.println(">> "+ expreStr);
    }//GEN-LAST:event_parIzqActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        expreStr= "";
        pantalla.setText(expreStr);
        System.out.println(">> "+ expreStr);
    }//GEN-LAST:event_clearActionPerformed

    private void multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiActionPerformed
        // TODO add your handling code here:
        expreStr= expreStr+ "*";
        pantalla.setText(expreStr);
        System.out.println(">> "+ expreStr);
    }//GEN-LAST:event_multiActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        // TODO add your handling code here:
        expreStr= expreStr+ "/";
        pantalla.setText(expreStr);
        System.out.println(">> "+ expreStr);
    }//GEN-LAST:event_divActionPerformed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
        // TODO add your handling code here:
        expreStr= expreStr+ "+";
        pantalla.setText(expreStr);
        System.out.println(">> "+ expreStr);
    }//GEN-LAST:event_sumaActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
        // TODO add your handling code here:
        expreStr= expreStr+ ".";
        pantalla.setText(expreStr);
        System.out.println(">> "+ expreStr);
    }//GEN-LAST:event_puntoActionPerformed

    private void cambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cambioActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
        // TODO add your handling code here:
        expreStr= expreStr+ "-";
        pantalla.setText(expreStr);
        System.out.println(">> "+ expreStr);
    }//GEN-LAST:event_restaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambio;
    private javax.swing.JPanel centro;
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton clear;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton div;
    private javax.swing.JButton dos;
    private javax.swing.JButton igual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton multi;
    private javax.swing.JPanel norte;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JTextField pantalla;
    private javax.swing.JButton parDer;
    private javax.swing.JButton parIzq;
    private javax.swing.JButton punto;
    private javax.swing.JButton resta;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton suma;
    private javax.swing.JPanel sur;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration//GEN-END:variables

    private String expreStr;
}
